### PR TITLE
attraction-page

### PR DESCRIPTION
**Pull request by ShoLn**
discord：ShoLn
姓名：林士堯
http://52.45.38.93:3000/
http://52.45.38.93:3000/attraction/23

### CODE REVIEW

**Comment by cwpeng** [comment]
There is no space between slider and navigator in mobile version. Fix it and leave comment for me to review again.

**Comment by ShoLn** [comment]
sorry, i dont understand , you mean there shouldn't have space between navigator and slider?

**Comment by cwpeng** [comment]
yes, in mobile version.

未命名-6

**Comment by ShoLn** [comment]
you mean the space between them is 0 px?  
or i should alternate it to 40px,
cause there is 40px in figma

截圖 2022-03-15 上午1 29 43

**Review by cwpeng — APPROVED** [review]
Thanks for your reminder. It's my fault. We should align with design, keep 40px space.

OK. Done.

**Comment by ShoLn** [comment]
ok thans!!

**Pull request merged**
