### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ShoLn**
姓名：林士堯
discord: ShoLn

http://52.45.38.93:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Your delay variable will not change back to false if I loaded last page of data, and it will block keyword search feature.

Fix this small issue and leave comment for me to review. If you cannot get my point, contact me to clarify it.

**Comment by ShoLn** [comment]
thanks for pointing out the problem , 
I add an  insertion at line 41 to change variable delay to false if the page is null,
and change the order of assigning variable delay to true in front of async function at scroll event and click event,
and i also found that variable wont change to false if api response error,  fixed at line 56,
it seems solving the problem , please let me know if there is another problem, 
thanks for reviewing!
http://52.45.38.93:3000/

**Comment by cwpeng** [comment]
Good fix. But there is another issue I just noticed. If I search 館, there should be only 2 pages, but we will load up to 4 pages of all attractions. Leave comment for me after correction.

**Comment by ShoLn** [comment]
its let scope problem. 
I change the global variable "keyword" in click event with "let", which only works for block scope,
I fixed it by delete "let" at line 97 and 98. 
it seems to solve the problem, thanks for reviewing again!  
please let me know if there is another problem
 http://52.45.38.93:3000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
